### ISSUE TITLE
Add a spinner when loading data

### ISSUE THREAD

**Issue by bruno-garcia** [NuGetTrends/nuget-trends#69]
At time, it takes more than a second to load the initial data to populate the graph.
TODO: Add a spinner while the SPA is waiting for the backend.

**Comment by joaopgrassi** [comment]
This could be done by us, to reduce the number of dependencies. It's fairly easy to implement and we can use a custom loading icon, like this one: https://codepen.io/ispal/pen/mVaaJe/. (need to check the license first.)

Something like this should be enough: https://nezhar.com/blog/create-a-loading-screen-for-angular-apps/

**Comment by bruno-garcia** [comment]
@joaopgrassi that's an awesome spinner btw ;)
